### ISSUE TITLE
Issue with JSON files

### ISSUE THREAD

**Issue by alkachur** [distantnative/field-multiselect#21] opened 2017-01-02 20:40 UTC
When I'm use few multiselect fields with JSON data, page is loading very slow. Even few times server gives me 503 error.
This starts after update to 2.3.0 and still preset in 2.4.1. version.
JSON data is static and don't generated on fly.
Any Ideas, why this can happend here we try to understand the problem

https://forum.getkirby.com/t/503-error-when-edit-page/5764/14

**Comment by distantnative** [comment] 2017-01-22 11:59
I'm just trying to have a look at this. No immediate fix comes to mind, from reading it, it sounds like the JS might get screwed up with many JSON multiselect fields on one page. Trying to reproduce it now...

**Comment by distantnative** [comment] 2017-01-22 12:19
Ok, I could already narrow it down. It does not seem to be a JS bug, but a PHP bug, specifically with `$this->value()` in the multiselectfield class, that just slows it down extremely

**Comment by distantnative** [comment] 2017-01-22 12:29
Hunting it down: The problem seems to be a general Kirby problem, it appears the same way with the checkboxes field, that multiselect is built on top of. I think it appears because Kirby check the options for each checkbox - and with JSON it means loading the JSON file for each checkbox again and again.

**Comment by distantnative** [comment] 2017-01-22 12:43
Has to be fixed in the Kirby panel itself as mentioned in the referenced issue. Will close this issue here, once the bug is fixed in the panel itself.

**Closed** 2017-03-22 14:29 UTC
Labels: wontfix

**Comment by distantnative** [comment] 2017-06-18 12:30
Will be fixed in the soon-to-be-released v2.5.0 of Kirby
